export const places = [
  {
    slug:'fort-kala-ghoda-mumbai', name:'Fort & Kala Ghoda', area:'South Mumbai · Heritage', number:'02', map:'Kala Ghoda, Fort, Mumbai', image:'gallery-cst.jpg', alt:'Victorian Gothic architecture in Mumbai near the Fort heritage district',
    title:'Fort & Kala Ghoda Mumbai: What to See | Detour', description:'Explore Fort and Kala Ghoda in Mumbai: a practical walking route through heritage architecture, museums, galleries, cafés and nearby landmarks.',
    lead:'Mumbai becomes wonderfully walkable here. Fort and Kala Ghoda compress grand civic architecture, galleries, libraries, museums and old cafés into a few rewarding streets.',
    time:'2–3 hours', pair:'Gateway + Colaba', best:'Morning or late afternoon', airport:'Longer cross-city trip',
    why:'This is the best Mumbai neighbourhood for travellers who like cities through their buildings. Victorian Gothic, Indo-Saracenic and Art Deco details sit beside working offices, bookstalls and cafés. The pleasure is not checking off one monument; it is noticing how the whole precinct fits together.',
    route:[['20 min','Start at Kala Ghoda','Orient yourself around the galleries and heritage façades before the streets become busy.'],['45 min','Walk toward the Oval','Follow the architecture past libraries, university buildings and the open edge of Oval Maidan.'],['45 min','Choose one deep stop','Pick a museum, gallery or heritage interior instead of rushing through several.'],['30+ min','Finish with a café','End in Fort or continue south toward Colaba if your airport buffer allows.']],
    options:[['60 minutes','Architecture sampler','Kala Ghoda, a short heritage loop and one café.'],['2–3 hours','The ideal walk','Add the Oval, a gallery or museum, and time to look up.'],['4–5 hours','South Mumbai chapter','Continue to Gateway, Colaba or Marine Drive.']],
    notes:[['Best for','Architecture, art, museums and slow urban walking.'],['Footwear','Pavements vary; comfortable closed shoes make the route easier.'],['Museum days','Opening days differ, so choose the indoor stop before leaving.'],['Traffic sense','Walk within the precinct; use a car only between distant neighbourhoods.']],
    layover:'Fort is far enough from BOM that the road journey must be treated as part of the plan. It works best with a generous daytime layover; when traffic is heavy, a Bandra or near-airport route may protect more actual city time.',
    source:'https://mumbaicity.gov.in/en/tourism/places-of-interest/', sourceLabel:'Mumbai City places of interest'
  },
  {
    slug:'bandra-fort-bandstand-mumbai', name:'Bandra Fort & Bandstand', area:'Bandra · Waterfront', number:'03', map:'Bandra Fort, Mumbai', image:'gallery-sealink.jpg', alt:'Bandra-Worli Sea Link viewed from Mumbai waterfront',
    title:'Bandra Fort & Bandstand: Local Guide | Detour', description:'Plan a visit to Bandra Fort and Bandstand with sea views, a short waterfront walk, nearby cafés, Google Maps directions and layover advice.',
    lead:'Bandra Fort gives you sea wind, old stone and the Sea Link in one frame. Bandstand adds the everyday Mumbai ritual: walking, talking and watching the light change.',
    time:'1–2 hours', pair:'Bandra villages + cafés', best:'Late afternoon to sunset', airport:'Closer than South Mumbai',
    why:'This is a strong choice when you want a recognisable Mumbai view without committing to the long run downtown. The fort ruins are compact, but their position at the tip of Bandra makes the landscape feel expansive. The neighbourhood behind them supplies the food, street life and personality.',
    route:[['25 min','Begin inside the fort garden','Walk the restored ruins and use the higher edges for Sea Link views.'],['30 min','Follow Bandstand','Take the promenade slowly rather than treating it as a road between stops.'],['30 min','Turn into Bandra','Continue toward Mount Mary, Ranwar or a café depending on your interests.']],
    options:[['45 minutes','Fort and view','A quick circuit with the Sea Link outlook.'],['90 minutes','Waterfront version','Add Bandstand and time for sunset.'],['3 hours','Make it Bandra','Continue through village lanes, murals and cafés.']],
    notes:[['Best moment','Late afternoon gives softer light, but sunset also brings crowds.'],['Heat','There is limited shade on parts of the waterfront.'],['Food','Save the meal for Bandra’s inner streets rather than the fort itself.'],['Respect','Bandstand is a neighbourhood space, not a staged tourist attraction.']],
    layover:'Bandra is often a more sensible layover choice than South Mumbai because it sits closer to BOM. Live traffic still decides everything: the Western Express Highway and local roads can change quickly around peak hours.',
    source:'https://www.incredibleindia.gov.in/en/maharashtra/mumbai/bandra-fort', sourceLabel:'Incredible India: Bandra Fort'
  },
  {
    slug:'marine-drive-mumbai', name:'Marine Drive', area:'South Mumbai · Waterfront', number:'04', map:'Marine Drive, Mumbai', image:'hero-skyline-main.jpg', alt:'Mumbai skyline and Marine Drive waterfront at dusk',
    title:'Marine Drive Mumbai: Best Way to Visit | Detour', description:'Visit Marine Drive in Mumbai with the best time, walking route, nearby places, Google Maps directions and realistic airport layover advice.',
    lead:'Marine Drive asks very little of you: walk, sit on the sea wall and watch Mumbai move around the curve. The simplicity is exactly why locals keep returning.',
    time:'45–90 minutes', pair:'Fort or Chowpatty', best:'Sunset or early morning', airport:'South Mumbai journey',
    why:'The promenade is a release valve for the city. Office workers, runners, families and travellers share the same edge of the Arabian Sea. At night the arc of lights earns its Queen’s Necklace nickname, but daylight is better for seeing the Art Deco skyline behind you.',
    route:[['20 min','Start near the southern curve','Walk north with the sea on your left and the skyline behind you.'],['20 min','Choose a place to sit','The visit improves when you stop moving and let the city pass.'],['25 min','Continue toward Chowpatty','Extend the walk for street food or turn inland toward the heritage district.']],
    options:[['30 minutes','Sea-air reset','A short walk and ten quiet minutes on the wall.'],['60–90 minutes','The ideal pause','Walk, sit and stay for changing light.'],['3 hours','Build a coastal route','Add Chowpatty, Malabar Hill or a South Mumbai meal.']],
    notes:[['Best light','Sunset is dramatic; early morning is calmer and cooler.'],['Monsoon','Expect spray, strong rain and temporary safety restrictions near rough water.'],['Food','Chowpatty has more snack options than the central promenade.'],['Safety','Use marked crossings; the road beside the promenade is fast and busy.']],
    layover:'Marine Drive is easy to enjoy once you reach it, but reaching South Mumbai is the expensive part of your time budget. Combine it with Fort, Gateway or Colaba rather than making a separate cross-city journey for one photograph.',
    source:'https://maharashtratourism.gov.in/districts/mumbai-city/', sourceLabel:'Maharashtra Tourism: Mumbai City'
  },
  {
    slug:'colaba-causeway-mumbai', name:'Colaba & the Causeway', area:'South Mumbai · Market', number:'05', map:'Colaba Causeway, Mumbai', image:'gallery-bazaar.jpg', alt:'Colourful market shopping in Mumbai',
    title:'Colaba Causeway Mumbai: What to Do | Detour', description:'Explore Colaba Causeway in Mumbai: shopping, cafés, heritage streets, a practical walking route, maps and honest layover timing.',
    lead:'Colaba works best as the neighbourhood behind the Gateway: busy stalls, old buildings, cafés, independent shops and side streets that reward curiosity.',
    time:'1–3 hours', pair:'Gateway of India', best:'Late morning or evening', airport:'South Mumbai journey',
    why:'The Causeway is not a pristine market experience, and that is part of its charm. Bargaining, traffic and narrow pavements sit beside institutions and cafés that have anchored the area for generations. Step away from the main road occasionally; quieter lanes reveal more of Colaba’s texture.',
    route:[['30 min','Walk in from the Gateway','Use the monument as your starting point and enter Colaba gradually.'],['35 min','Browse the Causeway','Look first, compare prices and bargain politely if you decide to buy.'],['35 min','Take a side-street pause','Choose a café or a quieter lane away from the market flow.'],['30+ min','Continue or turn back','Kala Ghoda is the natural extension when you have more time.']],
    options:[['45 minutes','Quick browse','The first Causeway stretch and one refreshment.'],['2 hours','Neighbourhood pace','Add side streets, shopping and a café.'],['4 hours','South Mumbai loop','Combine Gateway, Colaba and Kala Ghoda.']],
    notes:[['Bargaining','Agree on a price before accepting customisation or packaging.'],['Crowds','Keep valuables close where pavements narrow.'],['Food','Choose a busy, established café or restaurant for a longer stop.'],['Photography','Ask before photographing vendors or people at close range.']],
    layover:'Colaba only makes sense when your schedule already supports South Mumbai. It is easy to lose time browsing, so decide your return point before entering the market and let the airport buffer end the walk.',
    source:'https://maharashtratourism.gov.in/cave/elephanta/', sourceLabel:'Maharashtra Tourism: Mumbai attractions'
  },
  {
    slug:'csmt-heritage-quarter-mumbai', name:'CSMT Heritage Quarter', area:'Fort · Architecture', number:'06', map:'Chhatrapati Shivaji Maharaj Terminus, Mumbai', image:'gallery-cst.jpg', alt:'Chhatrapati Shivaji Maharaj Terminus Victorian Gothic facade',
    title:'CSMT Mumbai Heritage Quarter Guide | Detour', description:'See CSMT and Mumbai’s heritage quarter with an architecture route, practical timing, nearby stops, Google Maps and layover planning.',
    lead:'CSMT is both a working railway station and one of Mumbai’s defining buildings—a Victorian Gothic landmark shaped with Indian architectural details.',
    time:'1–2 hours', pair:'Fort + Crawford Market', best:'Morning or blue hour', airport:'Longer cross-city trip',
    why:'UNESCO describes CSMT as an exceptional meeting of Victorian Gothic Revival and Indian architectural traditions. That fusion is easiest to appreciate from outside: dome, turrets, pointed arches and stone carving, all operating as the backdrop to an intensely busy transport hub.',
    route:[['20 min','Find the full façade','Cross only at safe marked points and step back far enough to read the building as a whole.'],['25 min','Trace the civic axis','Continue past the municipal building and nearby heritage streets.'],['30 min','Choose market or Fort','Go toward Crawford Market for commerce or south into Fort for architecture and cafés.']],
    options:[['30 minutes','Exterior study','One careful look at the façade and civic buildings.'],['90 minutes','Heritage quarter','Add a short Fort walk or market edge.'],['3 hours','Old Bombay route','Connect CSMT, Fort, Kala Ghoda and a café.']],
    notes:[['Working station','Do not block commuter entrances while taking photographs.'],['Best view','The architecture reads best from across the road, where crossing discipline matters.'],['Detail','Look for Indian flora, fauna and craft within the Gothic composition.'],['Rush hour','The precinct becomes much harder to navigate during commuter peaks.']],
    layover:'CSMT is valuable for architecture lovers but sits deep in South Mumbai. Treat it as one stop within a Fort route, not a standalone airport run. If the roads are poor, a closer neighbourhood will give you more experience and less windscreen.',
    source:'https://whc.unesco.org/en/list/945', sourceLabel:'UNESCO: Chhatrapati Shivaji Terminus'
  },
  {
    slug:'elephanta-caves-mumbai', name:'Elephanta Caves', area:'Mumbai Harbour · Longer', number:'07', map:'Elephanta Caves, Maharashtra', directionsMap:'Gateway of India, Mumbai', directionsLabel:'Gateway ferry departure', directionsNote:'Driving directions lead to the Gateway ferry departure; open the separate island map before sailing.', image:'gallery-temple.jpg', alt:'Mumbai waterfront shrine at sunset, from the current Detour photo library',
    title:'Elephanta Caves from Mumbai: Layover Guide | Detour', description:'Plan Elephanta Caves from Mumbai: ferry route, time required, what to see, climbing considerations, official information and layover advice.',
    lead:'Elephanta is not a quick add-on. It is a ferry journey, an island climb and a UNESCO-listed complex of rock-cut caves whose great Shiva reliefs deserve a half day.',
    time:'At least half a day', pair:'Gateway of India', best:'Early morning', airport:'Only for long layovers',
    why:'The main cave contains monumental panels devoted to Shiva, including the celebrated three-faced form. The journey matters too: leaving the Gateway by boat changes your perspective on Mumbai before the island, steps and shaded cave interiors slow everything down.',
    route:[['60 min approx.','Ferry from the Gateway','Confirm the day’s service and weather before committing.'],['30+ min','Climb from the jetty','Allow for the approach, steps, heat and rests.'],['75 min','Give Cave 1 your attention','Read the major sculptural panels rather than rushing every chamber.'],['Return journey','Protect the last ferry and airport plan','Boat schedules and sea conditions outrank the rest of your itinerary.']],
    options:[['Too short','Under 5 hours city time','Choose Gateway and Colaba instead.'],['Half day','The minimum sensible visit','Ferry, climb, main caves and return.'],['Full day','The comfortable version','Add a slow island visit and South Mumbai meal.']],
    notes:[['Closed day','Official visitor guidance commonly lists Monday closure; verify before travel.'],['Mobility','The approach involves steps and uneven surfaces.'],['Weather','Ferries can be affected by monsoon and sea conditions.'],['Tickets','Fees and boat services change; check official information on the day.']],
    layover:'For most airport layovers, Elephanta is the wrong gamble. Attempt it only with a long daytime window, confirmed ferry operations and a generous return plan. A missed boat or weather change can consume the buffer that keeps your onward flight safe.',
    source:'https://whc.unesco.org/en/list/244', sourceLabel:'UNESCO: Elephanta Caves'
  },
  {
    slug:'dadar-flower-market-mumbai', name:'Dadar Flower Market', area:'Dadar · Early morning', number:'08', map:'Dadar Flower Market, Mumbai', image:'gallery-bazaar.jpg', alt:'Colourful flowers and market activity in Mumbai',
    title:'Dadar Flower Market Mumbai: Early Guide | Detour', description:'Visit Dadar Flower Market in Mumbai with the best time, respectful market route, nearby food, Google Maps directions and layover advice.',
    lead:'Dadar Flower Market is Mumbai already at full speed before breakfast: marigold bundles, rapid bargaining, handcarts and commuters threading through colour.',
    time:'45–75 minutes', pair:'Dadar + Worli', best:'Very early morning', airport:'Mid-city option',
    why:'This is an experience of working Mumbai, not a display arranged for visitors. The reward is rhythm: flowers arriving, being sorted and moving out across the city. Go early, keep out of the working lanes and let commerce happen around you.',
    route:[['15 min','Arrive and orient','Stand aside first and understand how people and goods are moving.'],['25 min','Walk the market edge','Follow the flow without stopping in loading or vendor spaces.'],['20 min','Pause for breakfast','Continue into Dadar for a simple local breakfast or chai.']],
    options:[['30 minutes','Colour and motion','One careful pass along the active edge.'],['60 minutes','The ideal visit','Add time to observe and a nearby breakfast.'],['2–3 hours','Everyday Mumbai','Pair with Dadar streets, Shivaji Park or Worli.']],
    notes:[['Go early','The market’s character is strongest in the morning.'],['Photography','Ask before close portraits and avoid turning work into spectacle.'],['Footing','Expect water, petals, crates and uneven walking space.'],['Buying','Small purchases are welcome; do not interrupt wholesale transactions.']],
    layover:'An early arrival can make Dadar a memorable alternative to sleeping at the airport, but only after immigration and luggage are resolved. It pairs well with central or western routes and avoids pushing all the way to the southern tip of the city.'
  },
  {
    slug:'dhobi-ghat-mumbai', name:'Dhobi Ghat', area:'Mahalaxmi · Everyday Mumbai', number:'09', map:'Dhobi Ghat, Mahalaxmi, Mumbai', image:'gallery-dharavi.jpg', alt:'Dense everyday neighbourhood and working life in Mumbai',
    title:'Dhobi Ghat Mumbai: Respectful Visitor Guide | Detour', description:'Visit Mumbai’s Dhobi Ghat respectfully: viewpoint, time needed, what to notice, nearby places, Google Maps directions and layover planning.',
    lead:'Dhobi Ghat is a vast working laundry, not an open-air performance. The right visit is brief, contextual and respectful of the people whose workplace you are viewing.',
    time:'30–60 minutes', pair:'Mahalaxmi + Worli', best:'Morning', airport:'Mid-city option',
    why:'From the public viewpoint, rows of wash pens and drying lines reveal the scale of a labour system that has served the city for generations. Context makes the difference: understand the work, keep your distance and resist treating residents or workers as props.',
    route:[['15 min','Use the public viewpoint','Begin from the established overlook near Mahalaxmi.'],['15 min','Look for the system','Notice sorting, washing, drying and movement rather than chasing portraits.'],['30+ min','Continue nearby','Pair the stop with Mahalaxmi, Worli or another central-Mumbai route.']],
    options:[['20 minutes','Viewpoint only','Enough for context and the broad view.'],['45 minutes','Thoughtful stop','Take time to understand the working landscape.'],['2 hours','Central Mumbai pair','Add Worli Sea Face or a nearby meal.']],
    notes:[['Respect','Do not enter residential or work areas without a legitimate local invitation.'],['Photography','Avoid close images of people without clear consent.'],['Best view','The public overlook provides scale without disrupting work.'],['Guide value','A local explanation prevents the visit becoming voyeuristic.']],
    layover:'Dhobi Ghat can fit a medium layover more easily than the far end of South Mumbai, especially when paired with Worli. The stop itself is short; road conditions and your airport return still determine whether it is sensible.'
  },
  {
    slug:'juhu-beach-mumbai', name:'Juhu Beach', area:'Juhu · Closer to BOM', number:'10', map:'Juhu Beach, Mumbai', image:'gallery-chai.jpg', alt:'Mumbai street-food pause near the western suburbs',
    title:'Juhu Beach Mumbai: Food, Sunset & Layovers | Detour', description:'Plan Juhu Beach in Mumbai for sunset and street food, with time options, safety notes, Google Maps directions and airport layover advice.',
    lead:'Juhu is Mumbai’s broad, democratic evening beach: families, walkers, vendors, street food and sunset gathering on the western edge of the city.',
    time:'1–2 hours', pair:'Bandra or western cafés', best:'Late afternoon', airport:'One of the closer options',
    why:'Juhu is not the city’s quietest beach; its appeal is atmosphere. Come for the crowd, the food and the long horizon. For layover travellers, its western-suburb location can preserve far more actual exploring time than a trip to South Mumbai.',
    route:[['25 min','Walk before the crowd peaks','Start along the open sand and get a sense of conditions.'],['35 min','Choose your street-food stop','Pick busy vendors and order one or two Mumbai classics.'],['25 min','Stay for the light','Finish at the waterline while keeping bags and valuables secure.']],
    options:[['45 minutes','Beach reset','A short walk and one snack.'],['90 minutes','The ideal Juhu visit','Add street food and sunset.'],['3 hours','Western neighbourhood route','Combine Juhu with Bandra or a café stop.']],
    notes:[['Sea safety','Follow local warnings and avoid entering rough or polluted water.'],['Food','Choose busy stalls with fast turnover; drink sealed or trusted water.'],['Crowds','Evenings and weekends can become extremely busy.'],['Weather','Monsoon changes beach conditions quickly.']],
    layover:'Juhu is one of the most practical ways to leave BOM without spending the day crossing Mumbai. It works especially well for late-afternoon or evening windows, provided peak-hour road traffic still leaves a protected return buffer.',
    source:'https://mumbaisuburban.gov.in/en/tourist-place/juhu-beach/', sourceLabel:'Mumbai Suburban District: Juhu Beach'
  },
  {
    slug:'bandra-villages-street-art-mumbai', name:'Bandra Villages & Street Art', area:'Bandra · Neighbourhood', number:'11', map:'Ranwar Village, Bandra, Mumbai', image:'gallery-chai.jpg', alt:'Local café and street culture in Mumbai',
    title:'Bandra Street Art & Village Walk | Detour', description:'Walk Bandra’s village lanes, street art, chapels and cafés with a practical route, Google Maps directions and Mumbai layover advice.',
    lead:'Behind Bandra’s traffic are village lanes with cottages, chapels, murals and small businesses—a layered neighbourhood best explored slowly and on foot.',
    time:'2–3 hours', pair:'Bandra Fort', best:'Morning or late afternoon', airport:'Closer than South Mumbai',
    why:'The appeal is contrast: old settlement patterns beside contemporary cafés and street art. Ranwar and nearby lanes are lived-in places, not an outdoor museum, so the best walk stays curious without intruding into homes or blocking narrow streets.',
    route:[['35 min','Begin around Ranwar','Walk quietly through public lanes and notice cottages, crosses and street patterns.'],['30 min','Follow the murals','Use street art as a thread, not a checklist; works change over time.'],['45 min','Add a café or bakery','Pause inside the neighbourhood instead of rushing to the next landmark.'],['45+ min','Continue to the sea','Finish at Bandstand or Bandra Fort if time allows.']],
    options:[['60 minutes','Village sampler','One compact lane loop and murals.'],['2–3 hours','The ideal Bandra walk','Add a café and unhurried exploration.'],['4 hours','Bandra chapter','Finish with the fort, Bandstand or sunset.']],
    notes:[['Residential space','Do not photograph inside homes, windows or private courtyards.'],['Street art','Murals evolve; treat the route as discovery rather than a fixed inventory.'],['Heat','Choose cooler hours because shade varies.'],['Food','Bandra offers options across budgets—pick the stop around your route, not vice versa.']],
    layover:'Bandra offers a strong balance of character and airport proximity. A local buddy is particularly useful here because the best lanes are easy to miss and a flexible route can switch between village, food and waterfront depending on traffic and weather.'
  },
  {
    slug:'powai-lake-mumbai', name:'Powai Lake & Cafés', area:'Powai · Closer to BOM', number:'12', map:'Powai Lake, Mumbai', image:'hero-skyline-side.jpg', alt:'Modern Mumbai skyline beside open water',
    title:'Powai Lake Mumbai: Practical Local Guide | Detour', description:'Explore Powai Lake and nearby cafés with a practical route, time options, Google Maps directions and advice for a shorter Mumbai airport layover.',
    lead:'Powai offers a modern, calmer Mumbai detour closer to the airport: lake views, landscaped streets and cafés without the full cross-city commitment.',
    time:'1–2 hours', pair:'Cafés + modern Mumbai', best:'Morning or sunset', airport:'Closer to BOM',
    why:'This is not the heritage postcard; it is a useful look at contemporary suburban Mumbai. The lake supplies breathing room while nearby streets make it easy to add coffee or a meal. It works best when time is limited and experience matters more than famous monuments.',
    route:[['25 min','Start at a public lake viewpoint','Check access and choose a safe, active stretch.'],['30 min','Walk the modern precinct','Notice the shift from water to planned streets and towers.'],['40 min','Choose a café stop','Use the meal as the anchor before returning to BOM.']],
    options:[['45 minutes','Lake and coffee','A compact reset between flights.'],['90 minutes','The ideal visit','Add a walk and relaxed café stop.'],['3 hours','Modern Mumbai route','Combine Powai with another near-airport experience.']],
    notes:[['Access','Lake-edge access varies; use established public viewpoints.'],['Mosquitoes','Carry repellent around water, especially near dusk.'],['Weather','Heavy rain can make walking sections impractical.'],['Expectation','Choose Powai for convenience and atmosphere, not old-city heritage.']],
    layover:'Powai is designed for the layover that is long enough to leave BOM but too short or traffic-sensitive for South Mumbai. It keeps the route compact, and a local can select the best accessible lake view and café for the exact hour.'
  },
  {
    slug:'bkc-mumbai', name:'BKC & Modern Mumbai', area:'BKC · Closer to BOM', number:'13', map:'Bandra Kurla Complex, Mumbai', image:'gallery-sealink.jpg', alt:'Contemporary infrastructure in modern Mumbai',
    title:'BKC Mumbai: Food, Art & Modern City Guide | Detour', description:'Explore BKC Mumbai for restaurants, contemporary architecture and cultural stops, with maps, time options and airport layover advice.',
    lead:'BKC is the polished, contemporary counterpoint to old Mumbai: offices, large cultural venues, public art and some of the city’s strongest restaurant choices.',
    time:'1–3 hours', pair:'Bandra or a meal', best:'Evening or event time', airport:'Very practical from BOM',
    why:'A business district may sound like an odd travel recommendation, but BKC is useful precisely because it is close to the airport and easy to shape around food, design or a scheduled cultural stop. It shows a version of Mumbai that heritage-only itineraries ignore.',
    route:[['30 min','Choose one cultural anchor','Check current exhibitions, performances or public spaces before arriving.'],['30 min','Walk the district','Use the architecture and public art as connective tissue.'],['60+ min','Make food the finish','Book or choose a restaurant appropriate to your available time.']],
    options:[['60 minutes','Meal-focused stop','One reliable restaurant and a short walk.'],['2 hours','Modern Mumbai sampler','Add architecture or a cultural venue.'],['4 hours','BKC plus Bandra','Continue west for neighbourhood life or waterfront.']],
    notes:[['Plan ahead','Venues and exhibitions change; check official schedules.'],['Walking','Blocks are large and heat can make short distances feel longer.'],['Budget','BKC often skews more expensive than street-food routes.'],['Best use','It shines when paired with a specific meal, event or exhibition.']],
    layover:'BKC is among the safest planning choices for a shorter layover because it avoids the longest downtown drive. It is less spontaneous than Colaba or Dadar, so pick the cultural or food anchor before leaving the airport.'
  },
  {
    slug:'worli-sea-face-mumbai', name:'Worli Sea Face', area:'Worli · Waterfront', number:'14', map:'Worli Sea Face, Mumbai', image:'gallery-sealink.jpg', alt:'Bandra-Worli Sea Link and Mumbai waterfront',
    title:'Worli Sea Face Mumbai: Waterfront Guide | Detour', description:'Visit Worli Sea Face for Sea Link views and a local promenade walk, with nearby stops, Google Maps directions and layover timing.',
    lead:'Worli Sea Face is a local waterfront pause with the Sea Link close enough to dominate the horizon—less ceremonial than Marine Drive and easier to pair with central Mumbai.',
    time:'45–75 minutes', pair:'Dadar or Mahalaxmi', best:'Early morning or sunset', airport:'Mid-city option',
    why:'The promenade gives you infrastructure, fishing history and everyday exercise culture in one stretch. It is a good connective stop between western suburbs and South Mumbai, but it is equally valid as the place where you simply sit and stop adding things.',
    route:[['20 min','Begin on the active promenade','Choose a safe public stretch with a clear Sea Link view.'],['20 min','Walk toward the fishing-village edge','Observe the older coastal life without entering private work areas.'],['20 min','Sit before moving on','Use the water as a genuine pause, not another drive-by photograph.']],
    options:[['30 minutes','Sea Link view','A compact photo and fresh-air stop.'],['60 minutes','The ideal pause','Walk, sit and watch the coast.'],['2–3 hours','Central Mumbai route','Pair with Dadar, Dhobi Ghat or a meal.']],
    notes:[['Monsoon','Strong waves and spray can make the edge unsafe; respect barricades.'],['Crossing','Use safe crossings on roads around the promenade.'],['Photography','Keep distance from working fishing spaces and ask before portraits.'],['Food','Plan the meal elsewhere in Worli, Dadar or Bandra.']],
    layover:'Worli can work well when your route already crosses central Mumbai. It is rarely worth a dedicated airport journey, but as a flexible pause between Bandra and the south it lets a buddy trim or extend the day without risking the return buffer.',
    source:'https://maharashtratourism.gov.in/districts/mumbai-city/', sourceLabel:'Maharashtra Tourism: Mumbai City'
  },
  {
    slug:'kanheri-caves-sanjay-gandhi-national-park-mumbai', name:'National Park & Kanheri', area:'North Mumbai · Longer', number:'15', map:'Kanheri Caves, Mumbai', image:'gallery-temple.jpg', alt:'Mumbai waterfront shrine at sunset, from the current Detour photo library',
    title:'Kanheri Caves & SGNP Mumbai Guide | Detour', description:'Plan Kanheri Caves and Sanjay Gandhi National Park in Mumbai: time required, route, official visitor information, maps and layover advice.',
    lead:'Kanheri pairs ancient Buddhist rock-cut caves with forest inside Mumbai. It is the city’s strongest alternative when you want history and nature instead of downtown.',
    time:'At least half a day', pair:'National park trails', best:'Early morning', airport:'Long but northbound',
    why:'The cave complex developed across centuries as a place of worship, learning and monastic life. Within Sanjay Gandhi National Park, the journey shifts from urban roads to forest and then stone chambers, cisterns, inscriptions and views over the green northern city.',
    route:[['Arrival','Enter through the national park','Confirm tickets, internal transport and cave access before setting out.'],['60+ min','Reach the cave complex','The internal journey is significant; do not treat it as a short stroll from the gate.'],['90 min','Explore selectively','Prioritise major prayer halls, cells, water systems and viewpoints.'],['Return','Leave margin inside the park','Internal transport and closing times must sit inside the airport plan.']],
    options:[['Too short','Under 4 hours city time','Choose Powai, Juhu or BKC instead.'],['Half day','Caves-focused visit','Park entry, Kanheri and a careful return.'],['Full day','Nature and heritage','Add a guided trail or slower park time.']],
    notes:[['Closed day','Official tourism guidance lists Kanheri Tuesday–Sunday; verify current operations.'],['Footwear','Expect steps, rock and heat or slippery monsoon surfaces.'],['Water','Carry enough drinking water and sun protection.'],['Wild space','Follow park rules and do not leave marked visitor areas.']],
    layover:'Kanheri needs a long daytime layover and disciplined planning. Although it is north of the central city, the park entrance, internal journey and caves all consume time. Confirm opening conditions before leaving BOM and keep a large airport buffer.',
    source:'https://www.incredibleindia.gov.in/en/maharashtra/mumbai/kanheri-caves', sourceLabel:'Incredible India: Kanheri Caves'
  }
];
